### ISSUE TITLE
When claim adjudicator is reassigned, what should we do with the previous adjudicator's claim header record?

### ISSUE THREAD

**Issue by joelhulen** [AzureCosmosDB/ClaimsProcessing#22]
## Background

When adding new claims, they are currently assigned to an Adjudicator. When this happens, a `ClaimHeader` document is stored in the `Adjudicator` container. That container has the `adjudicatorId` as its partition key. As we know, it is not possible to change the partition key value of a document once it's been saved to the container. Because of this, if the claim gets reassigned to a manager, according to the core business rules, the claim details record is updated, triggering a downstream update of the `ClaimHeader` document stored in the `Adjudicator` container, this time **with a new `adjudicatorId`** value (the value of the assigned manager). In some cases, this value might not change, like if the claim was originally assigned to a manager. But in most cases, it does. When the adjudicator is reassigned, we get a **new** `ClaimHeader` record stored in the `Adjudicator` container from the `AdjudicatorRepository.UpsertClaim` method that gets called by the `ClaimUpdated` Change Feed trigger.

## How this impacts UX behavior

In our example scenario, we have a claim that is assigned to an Adjudicator with a total amount of $12,670.12. The Adjudicator acknowledges the claim assignment and proposes a discount that exceeds the threshold set by the business rules ($500). When the Adjudicator proposed the claim, it was reassigned to the Manager for approval. Because the proposed discount exceeded the business rule threshold, the claim was automatically denied.

Because the claim was reassigned to a different Adjudicator (the Manager), and the `Adjudicator` container's partition key is set to the `adjudicatorId` value, a new `ClaimHeader` document was created. This means that the previous Adjudicator's document was not updated with the latest Claim Status and Total Amount values.

Here's the original Adjudicator's view:

![image](https://github.com/AzureCosmosDB/ClaimsProcessing/assets/5950304/2494127d-1c84-475e-bd79-c1c439c65fc3)

Notice that the Claim Details below is up to date, but the Adjudicator's `ClaimHeader` document (in the grid at the top of the image) still has the old Claim Status and Total Amount values.

Here's the Manager's view of the same claim:

![image](https://github.com/AzureCosmosDB/ClaimsProcessing/assets/5950304/7ee42800-99c2-475d-ac4c-a7d203de9519)

The Claim Status, Last Adjudicated Date, and Last Amount values are up to date since this `ClaimHeader` document receives updates as the claim flows through the system.

## How to address this

I propose making one of the following changes to address this issue:

1. When the claim is reassigned to a new Adjudicator, delete the previous Adjudicator's `ClaimHeader` document. This effectively "moves" the claim record to the reassigned Adjudicator (the Manager in this case).
2. Any time the claim is updated, update specific fields (Claim Status, Last Adjudicated Date, and Last Amount) in the `ClaimHeader` document for all other Adjudicators. This does not "move" the claim record from the original Adjudicator's grid but keeps those values up to date so they can still see the status.

I believe that the first option is the cleanest approach.

**Note:** This issue was first mentioned in #6

**Comment by joelhulen** [comment]
@sesmyrnov @luticm or @markjbrown do you have any input on how you want this addressed?

**Comment by sesmyrnov** [comment]
Hi @joelhulen - we reviewed this and we recommend to go with option #1 ( move Claim Header to new Adjudicator PK and delete the orig one). The challenge with this is implementing  TX boundary across different Adjudicator PK and likely need Transactional Outbox pattern. If you can implement it that way and document - this would be a great reference for customers.

**Comment by joelhulen** [comment]
Thank you for your input, @markjbrown and @sesmyrnov. I'll implement these changes today.

**Comment by joelhulen** [comment]
I just merged a PR that resolves this issue. Closing.
